name: Desafio de Variaveis e Escopos
on: workflow_dispatch

env:
  APP_NAME: "MeuAppIncrível" # 1. Variavel de escopo global

jobs:
  build_app:
    name: Build da Aplicacao
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: "v1.0.0" # 2. Variavel de escopo de job

    steps:
      - name: "Passo 1: Variaveis em Escopos Diferentes"
        env:
          STEP_TEMP: "Processando..." # 3. Variavel de escopo de step
        run: |
          echo "APP_NAME (Global): $APP_NAME"
          echo "BUILD_VERSION (Job): $
